baseURL = "https://pencilinthehand.com/"
languageCode = "en-us"
title = "Pencil In The Hand"
theme = "github.com/theNewDynamic/gohugo-theme-ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
googleAnalytics = ""
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon-black.svg"
  site_logo = "/images/favicon-white.svg"
  description = "I am a pencil in the hand of a writing God, writing love to all the world"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  show_reading_time = true

# Menu links
[[menu.main]]
  name = "About"
  url = "/about/"
